### PR TITLE
feat: add ssh client package required by maven release plugin

### LINKED ISSUE #378: Latest images don't have ssh causing maven-release-plugin to fail
Latest images don't have `ssh` which is required by the `maven-release-plugin`

I found the issue on `maven:3-eclipse-temurin-17`, but I spot checked several others and each had the same issue.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:3.0.1:prepare (default-cli) on project spring-cloud-starter-parent: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] /usr/bin/ssh -o StrictHostKeyChecking=accept-new: 1: /usr/bin/ssh: not found
[ERROR] fatal: Could not read from remote repository.
[ERROR] 
[ERROR] Please make sure you have the correct access rights
[ERROR] and the repository exists.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### PR DESCRIPTION
**Pull request by timothystone**
Consume upstream changes from dacr repository. Branch, resolve conflicts, and add openssh-clients to new images using appropriate package manager.

Update README SSH column.

Fixes #378

### CODE REVIEW

**Comment by timothystone** [comment]
Replaces #480

**Comment by timothystone-knsl** [comment]
h/t @dacr for the initial work. To collaborate with the upstream, recreated PR and rebased on new fork. Credit where credit is due. Thanks @dacr!

**Comment by timothystone** [comment]
Ready for workflows. 🙏

**Comment by timothystone-knsl** [comment]
@carlossg when does a change like this land in Docker Hub? And thanks for your patience and guidence in the PRs.

**Comment by carlossg** [comment]
I was thinking about not pushing this to dockerhub official images until there is a maven new version so it is not surprising existing users. It can be downloaded from my dockerhub and github regesitries already

**Pull request merged**
