### PR TITLE
Windows container support

### PR DESCRIPTION
**Pull request by slide**
This PR is a replacement for https://github.com/carlossg/docker-maven/pull/119. This includes the framework for building and publishing the Windows images to the maven dockerhub repo using GitHub Actions. For this to work, you would need to add secrets to this repository for DOCKER_USERNAME and DOCKER_PASSWORD. 

This also takes into account the recommendation from @jglick in the previous PR to make the Windows dockerfiles self contained in one directory to reuse the .ps1 and .xml files.

I have also added nanoserver container images in this PR, something that was not available previously because some bugs in the jdk for 8 and 11.

Sorry for the many commits, I can squash into a single commit and recreate the PR if desired.

### CODE REVIEW

**Comment by slide** [comment]
You can see the CI run from my fork here https://github.com/slide/docker-maven/commit/a041da50ab653193ac381e8cde6f54a19ea11311/checks?check_suite_id=279990849. It was pushing to my personal repo on dockerhub.

**Comment by slide** [comment]
Also, here is the dockerhub repo showing the published tags. https://hub.docker.com/r/slideomix/maven/tags

**Comment by carlossg** [comment]
thanks!

**Comment by carlossg** [comment]
I'm publishing them under https://hub.docker.com/u/csanchez/maven

**Pull request merged**
