### PR TITLE
Add --network host flag to linux command

### PR DESCRIPTION
**Pull request by skashmeri**
Hey, I ran into the issue of networking trying to run this locally as docker by default disallows ipv4 forwarding, thought it might be helpful to show the network flag which enables ipv4 forwarding for the host

### CODE REVIEW

**Comment by carlossg** [comment]
what error were you getting ? this works totally fine

**Comment by skashmeri** [comment]
"WARNING: IPv4 forwarding is disabled. Networking will not work."

unless you enable: net.ipv4.conf.all.forwarding with sysctl

**Comment by carlossg** [comment]
looks like a config setting in the host
https://stackoverflow.com/a/41453306/1815832

sharing networking with the host has other consequences

**Comment by skashmeri** [comment]
sorry the reason you need to pass the flag is there is no ingress via docker, its a comment in the cery link you shared, if you pass the flag it is a per cmd thing, obvs if you set it with systemctl you set it permanently which isnt in the scope of my change, without it the linux command wont work afaik.

**Pull request closed without merging**
