### PR TITLE
Add Liberica OpenJDK

### PR DESCRIPTION
**Pull request by Tri0L**

### CODE REVIEW

**Comment by carlossg** [comment]
can you run `github-action-generation.sh` and add the generated files?

Also does `generate-stackbrew-library.sh` throw any error ?

**Comment by Tri0L** [comment]
Both files throw:

```
./github-action-generation.sh
common.sh: line 8: jdk: unbound variable
```

**Comment by carlossg** [comment]
you must have an older bash

**Comment by carlossg** [comment]
can you add the references to the readme ?

**Comment by carlossg** [comment]
thanks!

**Comment by Tri0L** [comment]
Thank you! Could you please tell me, when it will be available in https://hub.docker.com/_/maven ?

**Comment by carlossg** [comment]
it won't be there because the parent image is not official

it will be in `csanchez/maven` and `ghcr.io/carlossg/maven`

**Pull request merged**
