### PR TITLE
Add variant based on Azul Zulu 11 Alpine image.

### PR DESCRIPTION
**Pull request by reitzig**
There is currently no image based on JDK 11 and Alpine. This PR closes that gap.

### CODE REVIEW

**Comment by reitzig** [comment]
Not sure where the tags on Docker Hub come from. Would propose the following:

 * 3.6.1-jdk-11-alpine, 3.6-jdk-11-alpine, 3-jdk-11-alpine
 * 3.6.1-azulzulu-alpine, 3.6-azulzulu-alpine, 3-azulzulu-alpine
 * 3.6.1-azulzulu-11-alpine, 3.6-azulzulu-11-alpine, 3-azulzulu-11-alpine

**Comment by carlossg** [comment]
azul based images can't be pushed to https://hub.docker.com/_/maven because azul images are not Docker official images.
I can merge but they won't be built

**Comment by reitzig** [comment]
That's unfortunate. :/

I've [inquired upstream](https://github.com/docker-library/openjdk/issues/334#issuecomment-523000274) as to why there still is no Alpine-based OpenJDK image.

**Comment by reitzig** [comment]
Side note: In our production thingy, we need to install `gcompat`. Is that a special need or would it always be needed?

**Comment by reitzig** [comment]
Since it seems OpenJDK 11 is in the Alpine repos after all, I created #121 .

**Pull request closed without merging**
