### PR TITLE
feat: add ssh client package needed by maven release plugin

### LINKED ISSUE #378: Latest images don't have ssh causing maven-release-plugin to fail
Latest images don't have `ssh` which is required by the `maven-release-plugin`

I found the issue on `maven:3-eclipse-temurin-17`, but I spot checked several others and each had the same issue.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:3.0.1:prepare (default-cli) on project spring-cloud-starter-parent: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] /usr/bin/ssh -o StrictHostKeyChecking=accept-new: 1: /usr/bin/ssh: not found
[ERROR] fatal: Could not read from remote repository.
[ERROR] 
[ERROR] Please make sure you have the correct access rights
[ERROR] and the repository exists.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### PR DESCRIPTION
**Pull request by timothystone-knsl**
Consume upstream changes from dacr repository. Branch, resolve conflicts, and add openssh-clients to
new images using appropriate package manager.

Update README SSH column.

Fixes #378

### CODE REVIEW

**Comment by carlossg** [comment]
thanks, I don't have permission to update the PR, can you change the line 
https://github.com/carlossg/docker-maven/blob/main/tests/tests.bats#L169
to `assert_success` ?

**Comment by timothystone-knsl** [comment]
> liberica is failing
...snip...
@carlossg Liberica failures in CentOS only. Looks related to this comment on [ServerFault](https://serverfault.com/a/1161904). Looking at path to resolution.

**Comment by timothystone-knsl** [comment]
> > liberica is failing
> > ...snip...
> 
> @carlossg Liberica failures in CentOS only. Looks related to this comment on [ServerFault](https://serverfault.com/a/1161904). Looking at path to resolution.
> 
> Working on it.

@carlossg so it appears that Liberica has not updated the CentOS images in three months. That's fine... I guess. But this change appears to about two weeks old and Liberica may drop a change. I'll try to monitor it.

I've got a patch inbound for your review based on the idea proposed in the ServerFault comment. Going to test it locally, then push.

**Comment by timothystone-knsl** [comment]
> > > liberica is failing
> > > ...snip...
> > 
> > 
> > @carlossg Liberica failures in CentOS only. Looks related to this comment on [ServerFault](https://serverfault.com/a/1161904). Looking at path to resolution.
> > Working on it.
> 
> @carlossg so it appears that Liberica has not updated the CentOS images in three months. That's fine... I guess. But this change appears to about two weeks old and Liberica may drop a change. I'll try to monitor it.
> 
> I've got a patch inbound for your review based on the idea proposed in the ServerFault comment. Going to test it locally, then push.

It's far more complicated. Liberica CentOS distros are building from 7.9.2009 [which is EOL](https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/) and not getting security updates.

How does the project determine removal of build support when upstream projects get stale?

**Comment by carlossg** [comment]
I'll remove them

**Comment by timothystone-knsl** [comment]
> I'll remove them

Do you want me to remove them from PR, or is there another process to handle post PR merge?

**Comment by carlossg** [comment]
when #481 is merged you'll need to rebase and solve conflicts

**Comment by timothystone-knsl** [comment]
Working on the update.

**Comment by timothystone-knsl** [comment]
> Working on the update.

Ready to kick off the workflows I think.

**Comment by chtompki** [comment]
I could use this patch. Definitely +1 for it being migrated in

**Comment by carlossg** [comment]
@timothystone could you allow maintainers edits to the PR as I'd like to squash this into one commit and rebase it? 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by timothystone-knsl** [comment]
> @timothystone could you allow maintainers edits to the PR as I'd like to squash this into one commit and rebase it? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

Of course. Working on it.

**Comment by timothystone-knsl** [comment]
I can recreate on a "properly forked" repository if necessary. Sorry for the mess.

**Comment by timothystone-knsl** [comment]
Closing. See #482.

**Pull request closed without merging**
