### PR TITLE
Add jdk-11 and jdk-11-slim images

### LINKED ISSUE #79: Add support for OpenJDK 11
I opened a PR https://github.com/docker-library/openjdk/pull/186 against OpenJDK docker to support OpenJDK 11. It would be great to support this in Maven as well. I'll put together a PR for this but can't be merged until the official OpenJDK image supports it.

### PR DESCRIPTION
**Pull request by risdenk**
Based on PR #66 and fixes #79.

This needs to wait for https://github.com/docker-library/openjdk/pull/186 since it requires openjdk 11 docker images.

### CODE REVIEW

**Comment by risdenk** [comment]
Openjdk 11 images were merged and the official library now has them available.

**Comment by risdenk** [comment]
@carlossg - FYI think this is ready for review

**Comment by carlossg** [comment]
LGTM 

```
$ TAG=jdk-11 bats tests
 ✓ jdk-11 build image
 ✓ jdk-11 build test image
 ✓ jdk-11 create test container
 ✓ jdk-11 create test container (-u 11337:11337)
 ✓ jdk-11 settings.xml is setup
 ✓ jdk-11 repository is created
 ✓ jdk-11 generate sample project
 ✓ jdk-11 generate sample project (-u 11337:11337 -w /tmp --tmpfs /tmp -e HOME=/tmp)

8 tests, 0 failures

$ TAG=jdk-11-slim bats tests
 ✓ jdk-11-slim build image
 ✓ jdk-11-slim build test image
 ✓ jdk-11-slim create test container
 ✓ jdk-11-slim create test container (-u 11337:11337)
 ✓ jdk-11-slim settings.xml is setup
 ✓ jdk-11-slim repository is created
 ✓ jdk-11-slim generate sample project
 ✓ jdk-11-slim generate sample project (-u 11337:11337 -w /tmp --tmpfs /tmp -e HOME=/tmp)

8 tests, 0 failures
```

**Comment by risdenk** [comment]
Thanks @carlossg!

**Pull request merged**
