### PR TITLE
Create windows Dockerfile generator and add images

### PR DESCRIPTION
**Pull request by slide**
This adds a powershell script to generate the Windows Dockerfiles and adds some additional images (including a fix for #236). To generate the Windows Dockerfiles, you can run:

.\windows-assets\generate-windows-files.ps1 -MavenVersion '3.9.0' -MavenHash 'THEHASHFORMAVEN.ZIP'

This will generate the directories, Dockerfiles and github action templates for the items defined in windows-image-configs.json.

### CODE REVIEW

**Comment by slide** [comment]
Looks like ltsc2022 isn't supported on GH Actions

**Comment by slide** [comment]
I guess a shell script would be better then?

**Comment by carlossg** [comment]
yeah for the generation definitely

I'm moving the linux images to use one main image to build and use `COPY --from` in the other ones based on Docker recommendation
https://github.com/docker-library/official-images/pull/14083#issuecomment-1433740677

I have some work in progress that will push soon.
I don't know if something like this is possible in Windows

**Comment by slide** [comment]
Ok, I'll wait and see what it looks like.

**Pull request closed without merging**
