### PR TITLE
Add variant with OpenJDK 11 and Alpine.

### PR DESCRIPTION
**Pull request by reitzig**
Another attempt at providing a JDK 11 + Alpine image, this one using only official stuff.

cf. #120

### CODE REVIEW

**Comment by carlossg** [comment]
I'm not sure this should be added given the direction the upstream openjdk base image took
See https://github.com/docker-library/openjdk/pull/322

**Comment by reitzig** [comment]
I can't say I can follow all those discussions in detail, but it seems to me that this here approach avoids musl (?) and seems ratified by the Alpine maintainers at least (since OpenJDK 11 is taken from the main repos). 

The main part of the post you link seems to have happened before Alpine 3.10, which was when OpenJDK was re-introduced to the repos.

**Comment by reitzig** [comment]
I can't say I can follow all those discussions in detail, but it seems to me that this here approach avoids musl (?) and seems ratified by the Alpine maintainers at least (since OpenJDK 11 is taken from the main repos). 

The main part of the post you link seems to have happened before Alpine 3.10, which was when OpenJDK was re-introduced to the repos.

**Comment by reitzig** [comment]
For that matter, why not just use the APK [maven](https://pkgs.alpinelinux.org/package/edge/community/x86/maven) package?

**Comment by reitzig** [comment]
Indeed, this does what we need:

```Dockerfile
FROM alpine:3.10

RUN apk update \
 && apk add --no-cache \
        openjdk11-jdk=11.0.4_p4-r1 \
        gcompat=0.4.0-r0 \
        maven=3.6.1-r0
```

**Pull request closed without merging**
