### PR TITLE
Remove volume declaration

### LINKED ISSUE #35: Add "Packaging a local repository with the image" paragraph to dockerhub [Feature Request]
There is no comments about /root/.m2 folder being a volume right now in dockerhub page. It can be extremely frustrating to debug.

### PR DESCRIPTION
**Pull request by carlossg**
It's a source of confusion for most users

Fixes #35 #32 #24 #11 

@tianon WDYT would this be a reasonable change for the next release of the official images?

### CODE REVIEW

**Comment by XPLOT1ON** [comment]
@carlossg any plans on merging this early? I'm looking forward to this commit. It will be very useful for my current project setup.

**Comment by tianon** [comment]
Yeah, that's probably sane -- this one is a bit iffy as a volume since configuration often goes in `~/.m2` as well, right?

**Comment by carlossg** [comment]
yes, the jar cache goes into `~/.m2/repository/` but even then people want to build images with cached jars inside too

**Comment by ibnesayeed** [comment]
Thanks for this change finally. It was giving more surprises otherwise and there was no way to undo the declaration in any subsequent Dockerfile. With the introduction of multi-stage builds JAR caches are not an issue any more, instead they are rather helpful.

**Comment by kbrazulewicz** [comment]
@carlossg when can we expect publishing new images without volume.

**Comment by carlossg** [comment]
https://github.com/docker-library/official-images/pull/3779

**Pull request merged**
