### PR TITLE
Update "generate-stackbrew-library.sh" to generate appropriate Architectures values (and use the new RFC 2822-based format)

### LINKED ISSUE #45: supprot arm64 architecture
I make maven image from arm64v8/openjdk:9-jdk to support arm64 and it build successed, so I want to konw maven can supprot arm64 architecture? if it can be support arm64 architecture we can add to update.

### PR DESCRIPTION
**Pull request by tianon**
I tried to match your `branch` logic, but not sure I got it 100% correct (and not 100% sure how you're using those bits either :innocent:).

I'm happy to make the official-images PR for this once it's merged too, if you'd like! :+1:

Closes #45

### CODE REVIEW

**Comment by tianon** [comment]
Here's what the output of this looks like:
```console
$ ./generate-stackbrew-library.sh
Maintainers: Carlos Sanchez <carlos@apache.org> (@carlossg)
GitRepo: https://github.com/carlossg/docker-maven.git

Tags: 3.5.0-jdk-7, 3.5-jdk-7, 3-jdk-7
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: 4b6cf057428dec330e39af811b54a6abd000402a
Directory: jdk-7

Tags: 3.5.0-jdk-7-alpine, 3.5-jdk-7-alpine, 3-jdk-7-alpine
Architectures: amd64
GitCommit: bdcedecba28295e7fc91256c9e58b0cc1f69ed57
Directory: jdk-7-alpine

Tags: 3.5.0-jdk-7-slim, 3.5-jdk-7-slim, 3-jdk-7-slim
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: afebe58fedee70782887d8bce0fdf808851593fd
Directory: jdk-7-slim

Tags: 3.5.0-jdk-8, 3.5.0, 3.5-jdk-8, 3.5, 3-jdk-8, 3, latest
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: 7fe1595b23769f777515ae3beca30003349a5ebb
Directory: jdk-8

Tags: 3.5.0-jdk-8-alpine, 3.5.0-alpine, 3.5-jdk-8-alpine, 3.5-alpine, 3-jdk-8-alpine, alpine
Architectures: amd64
GitCommit: bdcedecba28295e7fc91256c9e58b0cc1f69ed57
Directory: jdk-8-alpine

Tags: 3.5.0-jdk-8-slim, 3.5.0-slim, 3.5-jdk-8-slim, 3.5-slim, 3-jdk-8-slim, slim
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: afebe58fedee70782887d8bce0fdf808851593fd
Directory: jdk-8-slim

Tags: 3.5.0-jdk-9, 3.5-jdk-9, 3-jdk-9
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: 4b6cf057428dec330e39af811b54a6abd000402a
Directory: jdk-9

Tags: 3.5.0-jdk-9-slim, 3.5-jdk-9-slim, 3-jdk-9-slim
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: afebe58fedee70782887d8bce0fdf808851593fd
Directory: jdk-9-slim

Tags: 3.5.0-ibmjava-8, 3.5.0-ibmjava, 3.5-ibmjava-8, 3.5-ibmjava, 3-ibmjava-8, 3-ibmjava, ibmjava
Architectures: amd64, i386, ppc64le, s390x
GitCommit: 4b6cf057428dec330e39af811b54a6abd000402a
Directory: ibmjava-8

Tags: 3.5.0-ibmjava-8-alpine, 3.5.0-ibmjava-alpine, 3.5-ibmjava-8-alpine, 3.5-ibmjava-alpine, 3-ibmjava-8-alpine, ibmjava-alpine
Architectures: amd64
GitCommit: bdcedecba28295e7fc91256c9e58b0cc1f69ed57
Directory: ibmjava-8-alpine

Tags: 3.5.0-ibmjava-9, 3.5-ibmjava-9, 3-ibmjava-9
Architectures: amd64, i386, ppc64le, s390x
GitCommit: 4b6cf057428dec330e39af811b54a6abd000402a
Directory: ibmjava-9

Tags: 3.5.0-ibmjava-9-alpine, 3.5-ibmjava-9-alpine, 3-ibmjava-9-alpine
Architectures: amd64
GitCommit: bdcedecba28295e7fc91256c9e58b0cc1f69ed57
Directory: ibmjava-9-alpine
```

**Comment by tianon** [comment]
And the output of `diff -u <(bashbrew list maven | cut -d: -f2 | sort) <(bashbrew list <(./gene
rate-stackbrew-library.sh) | cut -d: -f2 | sort)` is empty, which is a good sign (means we didn't lose any tags in the conversion :+1:)

**Comment by carlossg** [comment]
the `branch` argument is no longer used now that everything is in master

**Comment by tianon** [comment]
Ah, that makes sense! :sweat_smile:

**Pull request merged**
