### PR TITLE
closes #25 - adding support for ibmjava 8 and 9

### LINKED ISSUE #25: [DISCUSSION] Support for JDKs other than OpenJDK.
I'm completely open to the answer here being no, but I simply wanted to ask the question if there might be appetite for official maven docker images built on top of more than just the open JDK. Maybe the Oracle JDK and the IBM JDK. We in Apache Commons regularly test our distributions on those and were thinking about including them in our Travis-CI builds.

Thoughts?

### PR DESCRIPTION
**Pull request by chtompki**
I think this could accommodate what I was getting at in #25. That said, I'm ok with you closing the PR and saying no go as well.

Cheers,
-Rob

### CODE REVIEW

**Comment by chtompki** [comment]
Oh. It's worth noting that ibm seems to build their java sdk ubuntu  images without `curl` installed, so in addition to your maven provisioning, I ran an `apt-get update && apt-get install -y curl` preceding the curl call to the maven .tar file.

**Comment by carlossg** [comment]
LGTM as long as you keep it up to date as needed

**Comment by carlossg** [comment]
you need to do now the alpine versions

**Comment by chtompki** [comment]
ok gotcha

**Pull request merged**
