### PR TITLE
Add ssh client package needed by maven release plugin

### LINKED ISSUE #378: Latest images don't have ssh causing maven-release-plugin to fail
Latest images don't have `ssh` which is required by the `maven-release-plugin`

I found the issue on `maven:3-eclipse-temurin-17`, but I spot checked several others and each had the same issue.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:3.0.1:prepare (default-cli) on project spring-cloud-starter-parent: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] /usr/bin/ssh -o StrictHostKeyChecking=accept-new: 1: /usr/bin/ssh: not found
[ERROR] fatal: Could not read from remote repository.
[ERROR] 
[ERROR] Please make sure you have the correct access rights
[ERROR] and the repository exists.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### PR DESCRIPTION
**Pull request by dacr**
Fix #378

### CODE REVIEW

**Comment by carlossg** [comment]
hi @dacr  thanks for the PR, if you could solve the conflicts and change the test in
https://github.com/carlossg/docker-maven/blob/main/tests/tests.bats#L162-L165
I'll merge it for the next maven release

**Comment by ebarped** [comment]
Is this MR still active? if not, maybe we should create a new one implementing this change

**Comment by timothystone-knsl** [comment]
> hi @dacr thanks for the PR, if you could solve the conflicts and change the test in https://github.com/carlossg/docker-maven/blob/main/tests/tests.bats#L162-L165 I'll merge it for the next maven release

Open #480 to resolve conflicts. 🤞

**Comment by timothystone-knsl** [comment]
@carlossg with #480, I think this can be closed (for tidiness).

**Comment by timothystone** [comment]
> > hi @dacr thanks for the PR, if you could solve the conflicts and change the test in https://github.com/carlossg/docker-maven/blob/main/tests/tests.bats#L162-L165 I'll merge it for the next maven release
> 
> Open #480 to resolve conflicts. 🤞

@carlossg, please elaborate on what the tests are doing? Checking for GPG or SSH, both? I understand the statement, but don't understand the specific context the tests are running with regards to pass or failure.

**Comment by timothystone** [comment]
> > > hi @dacr thanks for the PR, if you could solve the conflicts and change the test in https://github.com/carlossg/docker-maven/blob/main/tests/tests.bats#L162-L165 I'll merge it for the next maven release
> > 
> > 
> > Open #480 to resolve conflicts. 🤞
> 
> @carlossg, please elaborate on what the tests are doing? Checking for GPG or SSH, both? I understand the statement, but don't understand the specific context the tests are running with regards to pass or failure.

I think the line references change? Should the `assert_failure` check on [L167-169](https://github.com/carlossg/docker-maven/blob/main/tests/tests.bats#L162-L165) be updated?

**Comment by carlossg** [comment]
this is the test change needed https://github.com/carlossg/docker-maven/pull/480#issuecomment-2230395647

closing in favour of #480

**Pull request closed without merging**
