### PR TITLE
feat: corretto-17

### PR DESCRIPTION
**Pull request by buchhaim**
Hey guys.

Here's PR for newly released amazoncorretto-17 as it was also requested by issue #222. Maven version still remains the same, so basically only base image has changed to ```amazoncorretto-17``` and also action-workflow is provided.

BR
David

### CODE REVIEW

**Comment by carlossg** [comment]
Can you add it to the readme and other places?
Just search for amazoncorretto-17

**Comment by buchheim** [comment]
Ah thanks, I've missed this. Is added in another commit.

**Comment by buchheim** [comment]
@carlossg : I've run ```git update-index --chmod=+x mvn-entrypoint.sh``` - perhaps this might fix the failing build?

**Comment by carlossg** [comment]
Thanks

**Comment by buchheim** [comment]
@carlossg: Thank you! Will you take care of doing changes for https://github.com/docker-library to publish the official image?

**Comment by buchheim** [comment]
@carlossg FYI - I've opened https://github.com/docker-library/official-images/pull/10938/commits/5a21292dbad75542185f859c62c92953611e6f86.

**Pull request merged**
